config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'

  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'show/index'
  get 'songs/countdown'
  get 'standalone_tracklists/index'

  # get 'top400/index'
  resources :shows do
  	resources :songs
  end
  
  root 'top400#index'

  resources :sessions, only: [:create, :new] do
    collection do
      get :logout
    end
  end

  resources :standalone_tracklists

  # get 'application/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id         :integer          not null, primary key
#  artist     :string(255)
#  title      :string(255)
#  album      :string(255)
#  bpm        :decimal(10, )
#  key        :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

 # show_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Song < ApplicationRecord
	has_many  :show_songs
	has_many  :shows, through: :show_songs
	has_many  :djs, through: :dj_shows
	has_many  :track_orders, through: :show_songs

	validates :artist, presence: true
	validates :title, presence: true


	# Sort all songs by the number of shows they have appeared in and the last time they were played
	def self.sort_by_play_count(number_of_songs = nil)
		# debugger
		sorted_songs = Song.all.order(play_count: :desc, updated_at: :asc)[0..number_of_songs]
	end

	def self.play_count_for_song(artist, title)
		Song.where(artist: artist).where(title: title).play_count
	end

	def self.process_song(row, show_id)
		title_row = row["Track Title"].present? ? row["Track Title"] : row["Title"]
    	song = Song.where(artist: row["Artist"]).where(title: title_row).first
    	unless song 
      		# validations needed for artist, title, and album being blank
      		song = Song.create!(artist: row["Artist"], title: title_row, album: row["Album"], bpm: row["BPM"], key: row["Key"])
    	end
    	song.increment!(:play_count)
    	dj_name = row["DJ"].present? ? row["DJ"] : "Olga"
    	dj = Dj.where(name: dj_name).first_or_create
    	ShowSong.create!(song_id: song.id, dj_id: dj.id, show_id: show_id, track_order: row["#"])
	end

	# def track_order(show)
	# 	show_songs.where(show_id: show.id).track_order
	# end
	# def play_count_for_song
	# 	play_count
	# end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
	def new 
		# debugger
		# form_for_var = [@show, @show.songs.build]
        @song = Song.find(params[:song_id])
    end 

	def create
		# debugger
		# form_for_var = [@show, @show.songs.build]
    	@show = Show.find(params[:show_id])
    	@song = @show.songs.create(song_params)
    	redirect_to show_path(@show)
 	end

	def update
		debugger
		@song = Song.find(params[:id])
	 
		if @song.update(song_params)
			debugger
		    redirect_to @song.show
	  	else
	    	render 'edit'
	  	end
	end

	def show
		@song = Song.find(params[:id])
	end

	def edit
		@song = Song.find(params[:id])
		@show = @show.nil? ? @song.show : @show 
		@form_for_var = :song
		@method = "patch"
		@url = show_song_path(@show)
	end

	def destroy
	    @show = Show.find(params[:show_id])
    	@song = @show.songs.find(params[:id])
    	@song.destroy
    	redirect_to show_path(@show)
  	end

  	def countdown
  		@sorted_songs = Song.sort_by_play_count(400)
  	end
 
	private

		def song_params
			params.require(:song).permit(:artist, :title, :album, :bpm, :key)
		end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_mini_countdown.html.erb
<div id= "mini_countdown_container" class = "draggable box">
	<div class = "box_header"> 
		<p>
			<%=t('countdown')%>
		</p>
	</div>
	<div id = "mini_countdown">
	 	<%= render 'songs/songs_table', songs: Song.sort_by_play_count(3) %>
	 	<% song_count = Song.all.size %>
	 	<div class = "link_container">
			<%= link_to "#{song_count} more tracks...", songs_countdown_path %>
		</div>
	</div>
</div>

app/views/songs/_song_cell.html.erb
<tr class = "song_cell">
	  <td><%= order_number %>.</td>
      <td>
      	<span class = "artist">
      		<%= song.artist %>
      	</span> - 
      	<span class = "title">
      		<%= song.title  %>,
      	</span>
      	<span class = "album">
      		<%= song.album  %>
      	</span>
      </td>   
</tr>

app/views/songs/_song_form.html.erb
<%= form_for(@form_for_var, method: @method, url: @url, id: song_form) do |f| %>
  <p>
    <%= f.label :artist %><br>
    <%= f.text_field :artist %>
  </p>
  <p>
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </p>
  <p>
    <%= f.label :album %><br>
    <%= f.text_area :album %>
  </p>
  <p>
    <%= f.label :bpm %><br>
    <%= f.text_area :bpm %>
  </p>
  <p>
    <%= f.label :key %><br>
    <%= f.text_area :key %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/songs/_songs_table.html.erb
<div id = "songs_table_container">
	<table id = "songs_table">
		<tr class = "songs_table_row">   
		</tr>
			<% @order_number = 0 %>
			<% songs.each do |song| %>
				<% if song.id.present? %>
					<% @order_number += 1 %>
					<%= render 'songs/song_cell', song: song, order_number: @order_number %>
				<% end %>
			 <% end %>
	</table>
</div>

app/views/songs/countdown.html.erb
<h2 id = "countdown_title">Countdown</h2>
 <%= render 'songs/songs_table', songs: @sorted_songs %>
<div class = "link_container">
	<%= link_to 'Back', root_path %>	
</div>

app/views/songs/edit.html.erb
<h1>Edit Song</h1>

<%= render 'song_form', var: @form_for_var, method: @method, url: @url %>

<%= link_to 'Back', show_songs_path %>