config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'

  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'show/index'
  get 'songs/countdown'
  get 'standalone_tracklists/index'

  # get 'top400/index'
  resources :shows do
  	resources :songs
  end
  
  root 'top400#index'

  resources :sessions, only: [:create, :new] do
    collection do
      get :logout
    end
  end

  resources :standalone_tracklists

  # get 'application/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/top400_controller.rb
class Top400Controller < ApplicationController
  def index
  end
end

app/helpers/top400_helper.rb
module Top400Helper
end

app/views/top400/_about.html.erb
<div id = "about_container" class = "draggable box" >
	<div class = "box_header"> 
		<p>
			<%=t('top_400')%>
		</p>
	</div>
	<p class = "description">
		<%= raw t('about') %>
	</p>
</div>

app/views/top400/_nav.html.erb
<div id = "nav_container" class = "draggable box" >
	<div class = "box_header"> 
	</div>
	<span id="shows_link" class = "nav_link">
    	<%= link_to 'Shows', shows_path %>
    	<%= fa_icon "smile-o" %>
    </span>
   	<span id="home_link" class = "nav_link">
    	<%= link_to 'Home', root_path %>  
    	<%= fa_icon "home" %>
    </span>
    <span id="countdown_link" class = "nav_link">
    	<%= link_to "Top 400 Tracks", songs_countdown_path %>
    	<%= fa_icon "sort-numeric-asc" %>
    </span>
</div>

app/views/top400/_nav_link.html.erb
<div id = "nav_container" class = "draggable box" >
	<div class = "box_header"> 
		<p>
			<%= t("nav.#{link}") %>
		</p>
	</div>
	<span id="#{link}_link" class = "nav_link">
    	<%= link_to path do %>
    		<%= fa_icon icon %>
    	<% end %>
    </span>
</div>

app/views/top400/_newtown_link.html.erb
<div id = "newtown_container" class = "draggable box">
	<div class = "box_header"> 
		<p>
			<%=t('newtown_link')%>
		</p>
	</div>
	<%= link_to image_tag(asset_path('newtownlogosmall.png')), 'http://www.newtownradio.com/shows/top-400/' %>
</div>

app/views/top400/_timer.html.erb
<div id = "timer_container" class = "draggable box">
	<div class = "box_header"> 
		<p>Next Show</p>
	</div>
		<h1 id = "timer">
			<%= next_show_time %>
		</h1>
	</div>
</div>

app/views/top400/index.html.erb
<div id = "page_container">
	<h1 id = "title">
	</h1>
	<% unless Show.future_shows(1).empty? %>
		<%= render 'shows/future_show_image' %>
	<% end %>
	<%= render 'songs/mini_countdown' %>
	<%= render 'shows/latest_shows' %>
	<% unless Show.all.empty? %>
		<%= render 'shows/latest_show_image' %>
	<% end %>
	<%= render 'about' %>
	<%= render 'timer' %>
	<%= render 'newtown_link' %>
</div>

<%= javascript_tag do %>
  makeDraggables();
<% end %>