config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'

  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'show/index'
  get 'songs/countdown'
  get 'standalone_tracklists/index'

  # get 'top400/index'
  resources :shows do
  	resources :songs
  end
  
  root 'top400#index'

  resources :sessions, only: [:create, :new] do
    collection do
      get :logout
    end
  end

  resources :standalone_tracklists

  # get 'application/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/show.rb
# == Schema Information
#
# Table name: shows
#
#  id                    :integer          not null, primary key
#  title                 :string(255)
#  date                  :date
#  image                 :string(255)
#  tracklist             :string(255)
#  link_to_soundcloud    :string(255)
#  link_to_newtown_radio :string(255)
#  description           :text(65535)
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#

require 'csv'

class Show < ApplicationRecord
	has_many :show_songs
	has_many :songs, through: :show_songs
	has_many :djs, through: :show_songs
	accepts_nested_attributes_for :djs, :reject_if => lambda { |dj| dj[:name].blank? }
	accepts_nested_attributes_for :songs

	# validates :title, presence: true
	# validates :date, presence: true
	# validates :flyer, presence: true, :unless => lambda { self.is_standalone = 1 }
	# validates :tracklist, presence: true, :if => lambda { self.is_standalone = 1 }

	# uncomment
	# validates :link_to_newtown_radio, presence: true

	has_attached_file :flyer, styles: { full: "1080x1080", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :flyer, content_type: /\Aimage\/.*\z/

	scope :not_standalone, -> { where(is_standalone: false) }
	scope :standalone, -> { where(is_standalone: true) }

	def djs 
		show_songs.map(&:dj).uniq
	end

	def djNames
		djs.pluck(:name).join(' , ')
	end

  def process_song(row)
    Song.process_song(row, id)
  end

  # Gets count of all shows 
	def self.number_of_shows
		not_standalone.all.size
	end

	# Gets latest shows that have already happened
	def self.latest_shows(number_of_shows = nil)
		not_standalone.where("date < ?", Date.current).order(date: :desc).limit(number_of_shows)
	end

	# Gets future shows that haven't happened yet sorted by soonest show
	def self.future_shows(number_of_shows)
		not_standalone.where("date >= ?", Date.current).order(date: :asc).limit(number_of_shows)
	end

	# Orders songs by track order for show 
	def songs_in_order
		show_songs.order(:track_order).map {|show_song| show_song.song }
	end

	def has_tracklist?
		tracklist.present?
	end

	def is_standalone?
		is_standalone == true
	end

	# Formats the shows date 
	def formatted_date 
		date.strftime("%A, %B %d @ 22:00")
	end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
	def index
		@shows = Show.all.not_standalone
		@tracklists = Show.all.standalone
	end

	def new
		authentication_required!
		# @user = SiteUser.all
		@show = Show.new
	end

	def create
		authentication_required!
		# @user = SiteUser.all
		Show.transaction do 
			@show = Show.create!(show_params)

		# if params[:djs]
		# 	params[:djs].each do |dj|
		# 		unless dj[:name].blank? 
		# 			@dj = Dj.where(name: dj[:name])
		# 			@dj = Dj.create(name: dj[:name]) if @dj.blank?
		# 			@show.djs.push(@dj)
		# 		end
		# 	end
		# end

		# uploaded_image = show_params[:image]
		# if uploaded_image
		# 	image_filename = sanitize_filename(uploaded_image.original_filename)
		# 	File.open(Rails.root.join('public', 'images', image_filename), 'wb') do |file|
		# 	  file.write(uploaded_image.read)
		# 	end
		# 	@show.image = image_filename
		# end

			uploaded_tracklist = show_params[:tracklist]
			if uploaded_tracklist 
				tracklist_filename = sanitize_filename(uploaded_tracklist.original_filename)
				File.open(Rails.root.join('public', 'tracklists', tracklist_filename), 'wb') do |file|
				  file.write(uploaded_tracklist.read)
				end
				tracklist_path = Rails.root + "public/tracklists/" + tracklist_filename
				CSV.foreach(tracklist_path, :headers => true) do |row|
					@show.process_song(row)
				end
			end
		end
		 
		if @show.save
		    redirect_to @show
	  	else
	    	render 'new'
	  	end
	end

	def update
		authentication_required!
		@user = SiteUser.all
		@show = Show.find(params[:id])
	 	
		if @show.update(show_params)
		    redirect_to @show
	  	else
	    	render 'edit'
	  	end
	end

	def show
	 	# debugger
		@show = Show.find(params[:id])
		authentication_required! if @show.is_standalone?
		@form_for_var = [@show, @show.songs.build]
	end

	def edit
		authentication_required!
		@user = SiteUser.all
		@show = Show.find(params[:id])
	end

	 def destroy
	 	authentication_required!
		@user = SiteUser.all
	    @show = Show.find(params[:id])
	    @show.destroy
	 
	    redirect_to shows_path
	end

	# def admin
	#  	authentication_required!
	#  	redirect_to shows_path if session[:current_user]
	#  	flash[:notice] = "Not Authorized to access this page, plese log in"
 #        redirect_to new_session_path
	# end

  # 	protected
		# def sanitize_filename(filename)
		# 	return filename.gsub!(/[^0-9A-Za-z.\-]/, '_')
		# end

	private
		def show_params
			params.require(:show).permit(:title, :date, :description, :tracklist, :link_to_soundcloud, :link_to_newtown_radio, :flyer, :is_standalone, djs_attributes: [:name])
		end
	
end

app/helpers/shows_helper.rb
module ShowsHelper

	# Gets the time of the next show
	def next_show_time
		now = DateTime.current
		if now.cweek % 2 == 0 
			week_of_show = now.at_beginning_of_week
		else
			week_of_show = now.next_week.at_beginning_of_week
		end
		next_show_start = week_of_show - 2.hours
		next_show_start.strftime("%A, %B %d @ %H:00")
	end
end

app/views/shows/_form.html.erb
<%= form_for :show, url: url, method: method do |f| %>

  <% if @show.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@show.errors.count, "error") %> prohibited
        this show from being saved:
      </h2>
      <ul>
        <% @show.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </p>

  <p>
    <%= f.label :is_standalone %>
    <%= f.check_box :is_standalone %><br>
  </p>

  <p>
    <%= f.label :flyer %><br>
     <%= f.file_field :flyer %>
  </p>

  <p>
    <%= f.label :link_to_soundcloud %><br>
    <%= f.text_field :link_to_soundcloud %>
  </p>

  <p>
    <%= f.label :link_to_newtown_radio %><br>
    <%= f.text_field :link_to_newtown_radio %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <h4>
  Tracklist
  </h4>
   <%= f.file_field :tracklist %>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/shows/_future_show_image.html.erb
<div id = "future_show_image_container" class = "draggable box">
	<div class = "box_header"> 
		<p>
			<%=t('future_show')%>
		</p>
	</div>
  <% next_show = Show.future_shows(1).first %>
  <%= link_to image_tag(asset_path("#{next_show.flyer}")), show_path(next_show) %>
</div>

app/views/shows/_latest_show_image.html.erb
<div id = "latest_show_image_container" class = "draggable box">
	<div class = "box_header"> 
		<p>
			<%=t('latest_show')%>
		</p>
	</div>
	<% latest_show = Show.latest_shows(1).first %>
	<%= link_to image_tag(asset_path("#{latest_show.flyer}")), show_path(latest_show) %>
</div>

app/views/shows/_latest_shows.html.erb
<div id = "latest_shows_container" class = "draggable box">
	<div class = "box_header"> 
		<p>
			<%=t('latest_shows')%>
		</p>
	</div>
	
	<table id= "latest_shows">
		<% Show.latest_shows(3).each do |show| %>
			  <td><%= link_to show.title, show_path(show) %></td>
			</tr>
		<% end %>
	</table>
	<div class = "link_container">
		<% number_of_shows = Show.latest_shows().size - 2 %>
		<%= link_to "#{number_of_shows} more shows...", shows_path %>
	</div>
</div>

app/views/shows/_show_cell.html.erb
  <tr>
    <td><%= show.formatted_date %></td>
    <td><%= show.description %></td>
    <% if session[:current_user] %>
        <td><%= link_to 'edit', edit_show_path(show) %></td>
        <td><%= link_to 'destroy', destroy_show_path(show) %></td>
	<% end %>
	<td>
		<div class = "show_cell draggable box">
			<div class = "box_header"> 
				<p>
					<%= link_to show.title, show_path(show) %>
				</p>
			</div>
			<%= link_to image_tag(asset_path("#{show.flyer}")), show_path(show) %>
		</div>
	</td>
  </tr>

app/views/shows/_show_description.html.erb
<div id = "show_description_container" class = "draggable box" >
	<div class = "box_header"> 
		<p>
			<%= show.title %>
		</p>
	</div>
	<p class = "show_description">
		<%= show.description %>
	</p>
</div>

app/views/shows/_show_flyer.html.erb
<div id = "show_flyer_container" class = "draggable box">
	<div class = "box_header"> 
		<p>
			<%=show.formatted_date%>
		</p>
	</div>
    <img src="<%= asset_path("#{show.flyer}") %>" />
</div>

app/views/shows/_show_nav.html.erb
<div id = "show_nav_container" class = "draggable box" >
	<div class = "box_header"> 
	</div>
	<span id="shows_link" class = "show_nav_link">
        <a href=<%= @show.link_to_soundcloud %>>soundcloud</a>
    </span>
   	<span id="home_link" class = "show_nav_link">
    	<a href=<%= @show.link_to_newtown_radio %>>Archive on Newtown Radio</a>
    </span>  
            <%= fa_icon "soundcloud" %>
  
  </div>
</div>

app/views/shows/_tracklist.html.erb
<div id= "tracklist_container" class="draggable box">
	<div class = "box_header"> 
		<p>
			<%=t('tracklist')%>
		</p>
	</div>
	<div class = "tracklist">
	 	<%= render 'songs/songs_table', songs: songs %>
	 	<% song_count = songs.size %>
	</div>
</div>

app/views/shows/edit.html.erb
<h1>Edit Show</h1>

<%= render 'form', method: :patch, url: show_path(@show) %>

<%= link_to 'Back', shows_path %>


<% if session[:current_user] %>
  <li><%= link_to 'Log OUT', logout_sessions_path %></li>
<% end %>

app/views/shows/index.html.erb
<div id = "shows_list_container"
  <h1>Listing shows</h1>
  <table id = "shows">
    <tr>
      <th>Title</th>
      <th>DJ</th>
      <th>Date</th>
      <th>Image</th>
      <th>Description</th>
    </tr>
   
    <% @shows.each do |show| %>
      <%= render 'show_cell', show: show %>

      <tr>
        <td><%= link_to show.title, show_path(show) %></td>
        <td><p><%= show.djNames%></p></td>
        <td><%= show.formatted_date %></td>
        <td><img src="<%= asset_path("#{show.flyer}") %>" /></td>
        <td><%= show.description %></td>
        <td><%= link_to 'edit', edit_show_path(show) %></td>
      </tr>
    <% end %>
  </table>

<% if session[:current_user] %>
  <div id = "tracklists_list_container"
  <h1>Listing tracklists</h1>
  <table id = "tracklists">
    <tr>
      <th>Title</th>
      <th>DJ</th>
      <th>Date</th>
      <th>Description</th>
    </tr>
   
    <% @tracklists.each do |tracklist| %>
      <tr>
        <td><%= link_to tracklist.title, show_path(tracklist) %></td>
        <td><p><%= tracklist.djNames%></p></td>
        <td><%= tracklist.formatted_date %></td>
        <td><%= tracklist.description %></td>
        <td><%= link_to 'edit', edit_show_path(tracklist) %></td>
      </tr>
    <% end %>
  </table>
<% end %>

  <div class = "link_container">
    <%= link_to 'Back', root_path %>  
    <%= link_to 'new show', new_show_path %>  
  </div>
</div>

<% if session[:current_user] %>
  <li><%= link_to 'Log OUT', logout_sessions_path %></li>
<% end %>

app/views/shows/new.html.erb
<h1>New Show</h1>
<%= render 'form', method: :post, url: shows_path %>
<%= link_to 'Back', shows_path %>

<% if session[:current_user] %>
  <li><%= link_to 'Log OUT', logout_sessions_path %></li>
<% end %>

app/views/shows/show.html.erb
<div id = "show_container">
	<%= render 'show_description', show: @show %>

	<% if @show.is_standalone? %>
		<p> Standalone tracklist </p>
	<% end %>

	<%= render 'top400/nav' %>

	<%= render 'top400/nav_link', link: "shows", icon: "smile-o 5x", path: shows_path %>
	<%= render 'top400/nav_link', link: "countdown", icon: "sort-numeric-asc 5x", path: songs_countdown_path %>
	<%= render 'top400/nav_link', link: "home", icon: "home 5x", path: root_path %>

	<% unless @show.is_standalone? %>
		<%= render 'show_flyer', show: @show %>
	<% end %>

	<% if @show.has_tracklist? %>
  		<%= render 'tracklist', songs: @show.songs_in_order %>
 	<% end %>

</div>

<%= javascript_tag do %>
  makeDraggables();
<% end %>

<% if session[:current_user] %>
  <li><%= link_to 'Log OUT', logout_sessions_path %></li>
<% end %>